// eslint-disable-next-line import/no-anonymous-default-export
export default [
    {
        id: 1,
        name: "Jakub Lejczak",
        title: "Koordynator Główny",
        shortTitle: "MO",
        description: "",
        img: "./core-team/jakub_lejczak.jpg",
        alt: "Jakub Lejczak, Organizator Główny",
        color: "red",
    },
    {
        id: 2,
        name: "Jakub Iwaszkiewicz",
        title: "Koordynator ds. Merytoryki",
        shortTitle: "TR",
        description: "",
        img: "./core-team/jakub_iwaszkiewicz.jpg",
        alt: "Jakub Iwaszkiewicz, Opiekun BIT Jam",
        color: "blue",
    },
    {
        id: 3,
        name: "Adrian Augustyn",
        title: "Koordynator ds. Grafiki",
        shortTitle: "Designer",
        description: "",
        img: "./core-team/adrian_augustyn.jpg",
        alt: "Jakub Lejczak, Organizator główny", /*rozwiniecie*/
        color: "red",
    },
    {
        id: 4,
        name: "Julia Gacal",
        title: "Koordynatorka ds. Kontaktu z Firmami",
        shortTitle: "FR",
        description: "",
        img: "./core-team/julia_gacal.jpg",
        alt: "Julia Gacal, FR Barter", /*rozwiniecie*/
        color: "blue",

    },
    {
        id: 5,
        name: "Karolina Badowska",
        title: "Koordynatorka ds. Promocji",
        shortTitle: "PR",
        description: "",
        img: "./core-team/karolina_badowska.jpg",
        alt: "Karolina Badowska, PR", /*rozwiniecie*/
        color: "red",
    },
    {
        id: 6,
        name: "Aleksandra Grochowska",
        title: "Koordynatorka ds. Logistyki",
        shortTitle: "LG",
        description: "",
        img: "./core-team/aleksandra_grochowska.jpg",
        alt: "Aleksandra Grochowska, LG", /*rozwiniecie*/
        color: "blue",
    },
    {
        id: 7,
        name: "Piotr Maciejończyk",
        title: "Koordynator ds. Rozrywki",
        shortTitle: "CR",
        description: "",
        img: "./core-team/piotr_maciejonczyk.jpg",
        alt: "Piotr Maciejończyk, CR", /*rozwiniecie*/
        color: "red",
    },
    {
        id: 8,
        name: "Julian Dobryniewski",
        title: "Koordynator ds. IT",
        shortTitle: "IT/LG",
        description: "",
        img: "./core-team/julian_dobryniewski.jpg",
        alt: "Julian Dobryniewski, IT/LG", /*rozwiniecie*/
        color: "blue",
    },
    {
        id: 9,
        name: "Jagoda Wierzbińska",
        title: "Przedstawicielka Zarządu",
        shortTitle: "Angel",
        description: "",
        img: "./core-team/jagoda_wierzbinska.jpg",
        alt: "Jagoda Wierzbińska, Opiekunka Projektu",
        color: "red",
    },
    {
        id: 10,
        name: "Michał Ślimak",
        title: "Przedstawiciel Zarządu",
        shortTitle: "Angel",
        description: "",
        img: "./core-team/michal_slimak.jpg",
        alt: "Michał Ślimak, Opiekun Projektu",
        color: "blue",
    },
    {
        id: 11,
        name: "Krzysztof Marszałek",
        title: "Koordynator ds. Kontaktu z Firmami",
        shortTitle: "FR",
        description: "",
        img: "./core-team/krzysztof_marszalek.jpg",
        alt: "Krzysztof Marszałek, Koordynator ds. Kontaktu z Firmami",
        color: "red",
    },
    {
        id: 12,
        name: "Jakub Kędzia",
        title: "Koordynator ds. Kontaktu z Firmami",
        shortTitle: "FR",
        description: "",
        img: "./core-team/jakub_kedzia.jpg",
        alt: "Jakub Kędzia, Koordynator ds. Kontaktu z Firmami",
        color: "blue",
    },
    ]